// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

func newRelease(db *gorm.DB, opts ...gen.DOOption) release {
	_release := release{}

	_release.releaseDo.UseDB(db, opts...)
	_release.releaseDo.UseModel(&model.Release{})

	tableName := _release.releaseDo.TableName()
	_release.ALL = field.NewAsterisk(tableName)
	_release.Title = field.NewString(tableName, "title")
	_release.Nfo = field.NewField(tableName, "nfo")
	_release.Size = field.NewField(tableName, "size")
	_release.Files = field.NewField(tableName, "files")
	_release.Filename = field.NewField(tableName, "filename")
	_release.Nuked = field.NewBool(tableName, "nuked")
	_release.Nukereason = field.NewField(tableName, "nukereason")
	_release.Category = field.NewField(tableName, "category")
	_release.Created = field.NewTime(tableName, "created")
	_release.Source = field.NewField(tableName, "source")
	_release.Requestid = field.NewField(tableName, "requestid")
	_release.Groupname = field.NewField(tableName, "groupname")
	_release.NzedbpreDump = field.NewTime(tableName, "nzedbpre_dump")

	_release.fillFieldMap()

	return _release
}

type release struct {
	releaseDo

	ALL          field.Asterisk
	Title        field.String
	Nfo          field.Field
	Size         field.Field
	Files        field.Field
	Filename     field.Field
	Nuked        field.Bool
	Nukereason   field.Field
	Category     field.Field
	Created      field.Time
	Source       field.Field
	Requestid    field.Field
	Groupname    field.Field
	NzedbpreDump field.Time

	fieldMap map[string]field.Expr
}

func (r release) Table(newTableName string) *release {
	r.releaseDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r release) As(alias string) *release {
	r.releaseDo.DO = *(r.releaseDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *release) updateTableName(table string) *release {
	r.ALL = field.NewAsterisk(table)
	r.Title = field.NewString(table, "title")
	r.Nfo = field.NewField(table, "nfo")
	r.Size = field.NewField(table, "size")
	r.Files = field.NewField(table, "files")
	r.Filename = field.NewField(table, "filename")
	r.Nuked = field.NewBool(table, "nuked")
	r.Nukereason = field.NewField(table, "nukereason")
	r.Category = field.NewField(table, "category")
	r.Created = field.NewTime(table, "created")
	r.Source = field.NewField(table, "source")
	r.Requestid = field.NewField(table, "requestid")
	r.Groupname = field.NewField(table, "groupname")
	r.NzedbpreDump = field.NewTime(table, "nzedbpre_dump")

	r.fillFieldMap()

	return r
}

func (r *release) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *release) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["title"] = r.Title
	r.fieldMap["nfo"] = r.Nfo
	r.fieldMap["size"] = r.Size
	r.fieldMap["files"] = r.Files
	r.fieldMap["filename"] = r.Filename
	r.fieldMap["nuked"] = r.Nuked
	r.fieldMap["nukereason"] = r.Nukereason
	r.fieldMap["category"] = r.Category
	r.fieldMap["created"] = r.Created
	r.fieldMap["source"] = r.Source
	r.fieldMap["requestid"] = r.Requestid
	r.fieldMap["groupname"] = r.Groupname
	r.fieldMap["nzedbpre_dump"] = r.NzedbpreDump
}

func (r release) clone(db *gorm.DB) release {
	r.releaseDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r release) replaceDB(db *gorm.DB) release {
	r.releaseDo.ReplaceDB(db)
	return r
}

type releaseDo struct{ gen.DO }

type IReleaseDo interface {
	gen.SubQuery
	Debug() IReleaseDo
	WithContext(ctx context.Context) IReleaseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReleaseDo
	WriteDB() IReleaseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReleaseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReleaseDo
	Not(conds ...gen.Condition) IReleaseDo
	Or(conds ...gen.Condition) IReleaseDo
	Select(conds ...field.Expr) IReleaseDo
	Where(conds ...gen.Condition) IReleaseDo
	Order(conds ...field.Expr) IReleaseDo
	Distinct(cols ...field.Expr) IReleaseDo
	Omit(cols ...field.Expr) IReleaseDo
	Join(table schema.Tabler, on ...field.Expr) IReleaseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReleaseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReleaseDo
	Group(cols ...field.Expr) IReleaseDo
	Having(conds ...gen.Condition) IReleaseDo
	Limit(limit int) IReleaseDo
	Offset(offset int) IReleaseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReleaseDo
	Unscoped() IReleaseDo
	Create(values ...*model.Release) error
	CreateInBatches(values []*model.Release, batchSize int) error
	Save(values ...*model.Release) error
	First() (*model.Release, error)
	Take() (*model.Release, error)
	Last() (*model.Release, error)
	Find() ([]*model.Release, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Release, err error)
	FindInBatches(result *[]*model.Release, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Release) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReleaseDo
	Assign(attrs ...field.AssignExpr) IReleaseDo
	Joins(fields ...field.RelationField) IReleaseDo
	Preload(fields ...field.RelationField) IReleaseDo
	FirstOrInit() (*model.Release, error)
	FirstOrCreate() (*model.Release, error)
	FindByPage(offset int, limit int) (result []*model.Release, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReleaseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r releaseDo) Debug() IReleaseDo {
	return r.withDO(r.DO.Debug())
}

func (r releaseDo) WithContext(ctx context.Context) IReleaseDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r releaseDo) ReadDB() IReleaseDo {
	return r.Clauses(dbresolver.Read)
}

func (r releaseDo) WriteDB() IReleaseDo {
	return r.Clauses(dbresolver.Write)
}

func (r releaseDo) Session(config *gorm.Session) IReleaseDo {
	return r.withDO(r.DO.Session(config))
}

func (r releaseDo) Clauses(conds ...clause.Expression) IReleaseDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r releaseDo) Returning(value interface{}, columns ...string) IReleaseDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r releaseDo) Not(conds ...gen.Condition) IReleaseDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r releaseDo) Or(conds ...gen.Condition) IReleaseDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r releaseDo) Select(conds ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r releaseDo) Where(conds ...gen.Condition) IReleaseDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r releaseDo) Order(conds ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r releaseDo) Distinct(cols ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r releaseDo) Omit(cols ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r releaseDo) Join(table schema.Tabler, on ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r releaseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r releaseDo) RightJoin(table schema.Tabler, on ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r releaseDo) Group(cols ...field.Expr) IReleaseDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r releaseDo) Having(conds ...gen.Condition) IReleaseDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r releaseDo) Limit(limit int) IReleaseDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r releaseDo) Offset(offset int) IReleaseDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r releaseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReleaseDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r releaseDo) Unscoped() IReleaseDo {
	return r.withDO(r.DO.Unscoped())
}

func (r releaseDo) Create(values ...*model.Release) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r releaseDo) CreateInBatches(values []*model.Release, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r releaseDo) Save(values ...*model.Release) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r releaseDo) First() (*model.Release, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Take() (*model.Release, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Last() (*model.Release, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Find() ([]*model.Release, error) {
	result, err := r.DO.Find()
	return result.([]*model.Release), err
}

func (r releaseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Release, err error) {
	buf := make([]*model.Release, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r releaseDo) FindInBatches(result *[]*model.Release, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r releaseDo) Attrs(attrs ...field.AssignExpr) IReleaseDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r releaseDo) Assign(attrs ...field.AssignExpr) IReleaseDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r releaseDo) Joins(fields ...field.RelationField) IReleaseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r releaseDo) Preload(fields ...field.RelationField) IReleaseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r releaseDo) FirstOrInit() (*model.Release, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) FirstOrCreate() (*model.Release, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) FindByPage(offset int, limit int) (result []*model.Release, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r releaseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r releaseDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r releaseDo) Delete(models ...*model.Release) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *releaseDo) withDO(do gen.Dao) *releaseDo {
	r.DO = *do.(*gen.DO)
	return r
}
