// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRelease = "releases"

// Release mapped from table <releases>
type Release struct {
	Name     string     `gorm:"column:name;primaryKey" json:"name"`
	Created  time.Time  `gorm:"column:created" json:"created"`
	Nuked    int32      `gorm:"column:nuked" json:"nuked"`
	Category NullString `gorm:"column:category" json:"category"`
	Nfo      NullString `gorm:"column:nfo" json:"nfo"`
}

// TableName Release's table name
func (*Release) TableName() string {
	return TableNameRelease
}
