// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReleasePre = "release_pre"

// ReleasePre mapped from table <release_pre>
type ReleasePre struct {
	Name         string     `gorm:"column:name;not null" json:"name"`
	Nfo          NullString `gorm:"column:nfo" json:"nfo"`
	Size         NullString `gorm:"column:size" json:"size"`
	Files        NullString `gorm:"column:files" json:"files"`
	Filename     NullString `gorm:"column:filename" json:"filename"`
	Nuked        int32      `gorm:"column:nuked" json:"nuked"`
	Nukereason   NullString `gorm:"column:nukereason" json:"nukereason"`
	Category     NullString `gorm:"column:category" json:"category"`
	Created      time.Time  `gorm:"column:created;not null" json:"created"`
	Source       string     `gorm:"column:source;not null" json:"source"`
	Requestid    NullString `gorm:"column:requestid" json:"requestid"`
	Groupname    NullString `gorm:"column:groupname" json:"groupname"`
	NzedbpreDump time.Time  `gorm:"column:nzedbpre_dump" json:"nzedbpreDump"`
}

// TableName ReleasePre's table name
func (*ReleasePre) TableName() string {
	return TableNameReleasePre
}
