// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTorrentRelease = "torrent_release"

// TorrentRelease mapped from table <torrent_release>
type TorrentRelease struct {
	Torrent []byte `gorm:"column:torrent;primaryKey" json:"torrent"`
	Release string `gorm:"column:release;primaryKey" json:"release"`
}

// TableName TorrentRelease's table name
func (*TorrentRelease) TableName() string {
	return TableNameTorrentRelease
}
